"""empty message

Revision ID: 35ee4016a25b
Revises: ffdc0a98111c
Create Date: 2023-05-16 03:33:02.584953

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35ee4016a25b'
down_revision = 'ffdc0a98111c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('first_name', sa.String(length=40), nullable=False))
        batch_op.add_column(sa.Column('last_name', sa.String(length=40), nullable=False))
        batch_op.create_unique_constraint(batch_op.f('uq_users_first_name'), ['first_name'])
        batch_op.create_unique_constraint(batch_op.f('uq_users_last_name'), ['last_name'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_users_last_name'), type_='unique')
        batch_op.drop_constraint(batch_op.f('uq_users_first_name'), type_='unique')
        batch_op.drop_column('last_name')
        batch_op.drop_column('first_name')

    # ### end Alembic commands ###