"""empty message

Revision ID: 8393b3ac9b23
Revises: a5cfe890710d
Create Date: 2023-05-31 18:20:25.808077

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8393b3ac9b23'
down_revision = 'a5cfe890710d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('businesses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('owner_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_businesses_owner_id_users'), 'users', ['owner_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('businesses', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_businesses_owner_id_users'), type_='foreignkey')
        batch_op.drop_column('owner_id')

    # ### end Alembic commands ###