"""empty message

Revision ID: 8dcb157227fc
Revises: 3ad06d2e1140
Create Date: 2023-05-26 12:08:58.821947

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8dcb157227fc'
down_revision = '3ad06d2e1140'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('images', schema=None) as batch_op:
        batch_op.add_column(sa.Column('full_url', sa.String(length=500), nullable=False))
        batch_op.add_column(sa.Column('small_url', sa.String(length=500), nullable=True))
        batch_op.drop_column('url')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('images', schema=None) as batch_op:
        batch_op.add_column(sa.Column('url', sa.VARCHAR(length=500), autoincrement=False, nullable=False))
        batch_op.drop_column('small_url')
        batch_op.drop_column('full_url')

    # ### end Alembic commands ###