"""empty message

Revision ID: d3a2ff351c74
Revises: 8dcb157227fc
Create Date: 2023-05-26 12:44:13.934921

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd3a2ff351c74'
down_revision = '8dcb157227fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('images', schema=None) as batch_op:
        batch_op.add_column(sa.Column('url_full', sa.String(length=500), nullable=False))
        batch_op.add_column(sa.Column('url_regular', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('url_small', sa.String(length=500), nullable=True))
        batch_op.drop_column('full_url')
        batch_op.drop_column('small_url')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('images', schema=None) as batch_op:
        batch_op.add_column(sa.Column('small_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('full_url', sa.VARCHAR(length=500), autoincrement=False, nullable=False))
        batch_op.drop_column('url_small')
        batch_op.drop_column('url_regular')
        batch_op.drop_column('url_full')

    # ### end Alembic commands ###