"""empty message

Revision ID: 6cb33579cf3e
Revises: d3a2ff351c74
Create Date: 2023-05-26 14:05:00.332204

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6cb33579cf3e'
down_revision = 'd3a2ff351c74'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('images', schema=None) as batch_op:
        batch_op.alter_column('url_full',
               existing_type=sa.VARCHAR(length=500),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('images', schema=None) as batch_op:
        batch_op.alter_column('url_full',
               existing_type=sa.VARCHAR(length=500),
               nullable=False)

    # ### end Alembic commands ###