"""empty message

Revision ID: cc44ec3ca2d5
Revises: 04c4e077d3e1
Create Date: 2023-05-16 04:23:18.567911

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc44ec3ca2d5'
down_revision = '04c4e077d3e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_locations', schema=None) as batch_op:
        batch_op.drop_column('type')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_locations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sa.VARCHAR(length=40), nullable=True))

    # ### end Alembic commands ###