"""empty message

Revision ID: 04c4e077d3e1
Revises: 3c57c7e8d125
Create Date: 2023-05-16 04:02:01.297458

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04c4e077d3e1'
down_revision = '3c57c7e8d125'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint('uq_users_first_name', type_='unique')
        batch_op.drop_constraint('uq_users_last_name', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_users_last_name', ['last_name'])
        batch_op.create_unique_constraint('uq_users_first_name', ['first_name'])

    # ### end Alembic commands ###